### ISSUE TITLE
How can I connect MySQL cluster outside kubernetes cluster?

### ISSUE THREAD

**Issue by lindao99** [oracle/mysql-operator#101]
how can I connect MySQL cluster outside kubernetes cluster？
I want connect MySQL by some tools like HeidiSQL.

**Comment by bweston92** [comment]
@lindao99 Kubernetes CLI tool can do port forwarding.

Term 1:
```
$ kubectl port-foward mydb 3306
```

Term 2:
```
$ mysql -hlocalhost -uroot -p
```

**Comment by bweston92** [comment]
This can be closed?
