### ISSUE TITLE
 "Error: failed to download "mysql-operator""

### ISSUE THREAD

**Issue by kiranmudemela** [oracle/mysql-operator#105]
Trying to install mysql-operator and it gives the following error 

bash-3.2$ helm init
$HELM_HOME has been configured at /Users/kiran/.helm.
Warning: Tiller is already installed in the cluster.
(Use --client-only to suppress this message, or --upgrade to upgrade Tiller to the current version.)
Happy Helming!
bash-3.2$ helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
bash-3.2$ helm install --name my-release mysql-operator
Error: failed to download "mysql-operator" (hint: running `helm repo update` may help)
bash-3.2$

**Comment by prydie** [comment]
Hi @kiranmudemela, it looks like you perhaps haven’t got the MySQL operator Git repo checked out locally. Could that be the case?

**Comment by CaptTofu** [comment]
HI Kiran (my son's name :) - what was the fix for you? I encountered this as well.

helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}

**Comment by kiranmudemela** [comment]
Hi Patrick,
I remember i had downloaded it instead of helm.


Download the file  mysql operator Steps :
git clone https://github.com/oracle/mysql­operator
­­­­­­­­­­­­­­­­­­­­­­­­­­­­
bash­3.2$ pwd /Users/kiran/mysqlop/mysql­operator
bash­3.2$ bash­3.2$ helm install ­­name my­release mysql­operator ­­set
rbac.enabled=true
NAME:   my­release

LAST DEPLOYED: Wed May 23 10:36:52 2018
NAMESPACE: default
STATUS: DEPLOYED
RESOURCES: ==> v1beta1/CustomResourceDefinition

Thanks
kiran

**Comment by JJSWAIN2018** [comment]
@ git clone https://github.com/oracle/mysql­operator gives error page 
i m also trying to resolve the same issue i.e installation mysql-operator 
Error: failed to download "mysql-operator" (hint: running `helm repo update` may help)
