### ISSUE TITLE
mysql-operator ready for PROD?

### ISSUE THREAD

**Issue by kiranmudemela** [oracle/mysql-operator#114]
checking if mysql-operator is ready for Production ? 

---Resources shows as v1beta1
RESOURCES:
==> v1beta1/
--------

bash-3.2$ helm install --name my-release mysql-operator --set rbac.enabled=true
NAME:   my-release
LAST DEPLOYED: Wed May 23 10:36:52 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/CustomResourceDefinition
NAME                                   AGE
mysqlclusters.mysql.oracle.com         5s
mysqlbackups.mysql.oracle.com          5s
mysqlrestores.mysql.oracle.com         5s
mysqlbackupschedules.mysql.oracle.com  5s

==> v1beta1/ClusterRole
mysql-operator  5s

==> v1beta1/ClusterRoleBinding
NAME            AGE
mysql-operator  4s
mysql-agent     4s

==> v1beta1/Deployment
NAME            DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
mysql-operator  1        1        1           0          4s

==> v1/Pod(related)
NAME                            READY  STATUS             RESTARTS  AGE
mysql-operator-6c4fdcb45-8bt6g  0/1    ContainerCreating  0         4s

==> v1/ServiceAccount
NAME            SECRETS  AGE
mysql-operator  1        6s
mysql-agent     1        6s

NOTES:
Thanks for installing the MySQL Operator.

Check if the operator is running with

kubectl -n mysql-operator get po

bash-3.2$

**Comment by prydie** [comment]
Hi @kiranmudemela,

Everyone's constraints around production readiness are of course different but I'd generally say not quite. The operator is in alpha and under active development. We'll shortly be releasing a breaking change in 0.2 to upgrade to MySQL 8.
