### ISSUE TITLE
Define version of mysqlServer image

### ISSUE THREAD

**Issue by jiribroulik** [oracle/mysql-operator#117]
Hey guys,

can you tell me how I can specify specific version of mysql image? Specifying a version under spec of mysqlcluster throws an error within mysql-operator.

**Comment by prydie** [comment]
Hi @jiribroulik,

I'm afraid v0.1 only supports MySQL 5.7.20-1.1.2 and v0.2 (which will be out shortly) will only support MySQL 8.0.11+. What version are you trying to use?

**Comment by jiribroulik** [comment]
5.7.22-1.1.5
about support. you think it will not work with this version I want? Or how could I make it work with this version? Thank you

**Comment by prydie** [comment]
For the initial release, we limited the supported version to the MySQL version we'd done our testing on. It should work, however, unfortunately, the operator will reject the version currently as you've found.

@owainlewis What do you think of creating a `release-0.1` branch based on the v0.1 tag and then using it to release a v0.1.1 with relaxed 5.7.x version constraints?

**Comment by prydie** [comment]
Hi @jiribroulik, we're going to release a version which supports 5.7.22.-1.1.5. You can track progress at #120.

**Comment by jiribroulik** [comment]
@prydie thank you.
