### ISSUE TITLE
Release a 0.1.1 release which relaxes restrictions for 5.7 clusters

### ISSUE THREAD

**Issue by owainlewis** [oracle/mysql-operator#120]
We enforce some very specific version requirements on the 0.1.0 release but this might cause issues for anyone wanting to stick on the 5.7 release branch (i.e if they need to update for a security patch etc).

Remove the validation in https://github.com/oracle/mysql-operator/blob/0.1.0/pkg/apis/mysql/v1/validate_cluster.go#L42 to allow users to upgrade to newer release image versions of MySQL 5.7. We then need to cut a 0.1.1 release with the changes.

**Comment by jiribroulik** [comment]
Hello @owainlewis 
Do you have any ETA on this please? Thank you

**Comment by simonlord** [comment]
@jiribroulik i've just released as 0.1.1: https://github.com/oracle/mysql-operator/releases/tag/0.1.1

Here's an example of specifying the version: https://github.com/oracle/mysql-operator/blob/0.1.1/examples/cluster/cluster-with-custom-version.yaml
