### ISSUE TITLE
Question about Percona support

### ISSUE THREAD

**Issue by devdattakulkarni** [oracle/mysql-operator#124]
This is more of a question rather than a feature request or a bug report.

In our use-case we are interested in using this operator with Percona Docker image. I was wondering if the operator will work as it is with Percona? If not, what all changes would be needed?

Thanks for your help.

**Comment by owainlewis** [comment]
Hi @devdattakulkarni 

We don't actively support Percona and so I can't comment on whether or not it would work (we've not yet tested anything other than the official MySQL image). We require InnoDB and [InnoDB cluster](https://dev.mysql.com/doc/refman/8.0/en/mysql-innodb-cluster-introduction.html). The most recent changes will be aimed at supporting MySQL 8.

We are certainly open to broadening the scope of this operator, but we haven't really considered it in enough depth to make any clear decisions either way. 

Thanks.
