### ISSUE TITLE
Need help troubleshooting 

### ISSUE THREAD

**Issue by ankurshah7** [oracle/mysql-operator#134]
I am following tutorial and need assistance troubleshooting.
I have minikube v0.27.0, kubectl server v1.10.0 client v1.10.4.
I cloned mysql-opeartor  ( master )
I created mysqlcluster myappdb but cannot get mysql password secret.

```
A@Ubuntu:~$ kubectl get mysqlcluster
NAME  	AGE
myappdb   17m

A@Ubuntu:~$ kubectl describe mysqlcluster
Name:     	myappdb
Namespace:	default
Labels:   	<none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"mysql.oracle.com/v1alpha1","kind":"MySQLCluster","metadata":{"annotations":{},"name":"myappdb","namespace":"default"}}

API Version:  mysql.oracle.com/v1alpha1
Kind:     	MySQLCluster
Metadata:
  Cluster Name:   	 
  Creation Timestamp:  2018-06-12T17:59:21Z
  Generation:      	1
  Resource Version:	10594
  Self Link:       	/apis/mysql.oracle.com/v1alpha1/namespaces/default/mysqlclusters/myappdb
  UID:             	5560579f-6e6a-11e8-9ec3-080027ca9ee4
Events:            	<none>

A@Ubuntu:~$ kubectl get secret myappdb-root-password -o jsonpath="{.data.password}"
Error from server (NotFound): secrets "myappdb-root-password" not found
```
Thanks,

**Comment by cisco-** [comment]
It seems there's an inconsistency between the operator and the resource definitions in the master branch. From what I can gather, the helm chart deploys version 0.1.0 of the operator which tries to listen for changes to the resources in version "v1", but the CRDs are in version v1alpha1, so the operator can't list them. 
Have a look at the log output of the operator pod. If it complains that it can't list the resources, then welcome, we're in the same boat :) 

```
I0612 18:37:57.321854       1 reflector.go:240] Listing and watching *v1.MySQLCluster from github.com/oracle/mysql-operator/pkg/generated/informers/externalversions/factory.go:72
E0612 18:37:57.322590       1 reflector.go:205] github.com/oracle/mysql-operator/pkg/generated/informers/externalversions/factory.go:72: Failed to list *v1.MySQLCluster: the server could not find the requested resource (get mysqlclusters.mysql.oracle.com)
I0612 18:37:57.322911       1 reflector.go:240] Listing and watching *v1.MySQLBackupSchedule from github.com/oracle/mysql-operator/pkg/generated/informers/externalversions/factory.go:72
E0612 18:37:57.323464       1 reflector.go:205] github.com/oracle/mysql-operator/pkg/generated/informers/externalversions/factory.go:72: Failed to list *v1.MySQLBackupSchedule: the server could not find the requested resource (get mysqlbackupschedules.mysql.oracle.com)
I0612 18:37:57.323984       1 reflector.go:240] Listing and watching *v1.MySQLRestore from github.com/oracle/mysql-operator/pkg/generated/informers/externalversions/factory.go:72
E0612 18:37:57.324550       1 reflector.go:205] github.com/oracle/mysql-operator/pkg/generated/informers/externalversions/factory.go:72: Failed to list *v1.MySQLRestore: the server could not find the requested resource (get mysqlrestores.mysql.oracle.com)
```

Is what I saw. To "fix" (and I'm using this term lightly) I removed the "Cluster" and uninstalled the operator with "helm delete --purge my-release", then modified the helm chart to again register "v1" by replacing all mentions of v1alpha1 with v1 in mysql-operator/templates/01-resources.yaml and then started from scratch. (Also note that the yaml to create the cluster also refers to "mysql.oracle.com/v1" instead of "mysql.oracle.com/v1alpha1" unlike yours. 

Anyway that did the trick for now, until a fix is in, I suppose 

HTH

**Comment by ankurshah7** [comment]
I followed @cisco- but did not 'Fix' - I think v1alpah1 is spread to  *.go files. I see following in mysql-operator logs.

```
ERROR: logging before flag.Parse: I0612 19:11:24.385350   	1 reflector.go:240] Listing and watching *v1.ConfigMap from github.com/oracle/mysql-operator/vendor/k8s.io/client-go/informers/factory.go:86
ERROR: logging before flag.Parse: E0612 19:11:24.386536   	1 reflector.go:205] github.com/oracle/mysql-operator/vendor/k8s.io/client-go/informers/factory.go:86: Failed to list *v1.ConfigMap: configmaps is forbidden: User
```

**Comment by prydie** [comment]
Hi @ankurshah7 and thanks @cisco-! I've opened https://github.com/oracle/mysql-operator/issues/135 which captures the root of the problem. We'll get an update out to the helm chart ASAP.

For now,  you should be able to fix the issue by editing the mysql-operator [Cluster]Role and granting it permissions to `['get', 'list', 'watch']` ConfigMaps.

**Comment by cisco-** [comment]
FWIW I also had to add permissions for "events"

**Comment by prydie** [comment]
Thanks, @cisco-. I picked up on that earlier and opened #136.

**Comment by ankurshah7** [comment]
I am K8s newbie - How to edit the mysql-operator [Cluster]Role and grant it permissions to ['get', 'list', 'watch'] ConfigMaps? Is it by editing templates/02-rbac.yaml ?

**Comment by JJSWAIN2018** [comment]
Hi , 
I getting the following error , when i create backup file . 
Error in syncHandler, re-adding "default/mysql-backup" to queue: no primaries found
github.com/oracle/mysql-operator/pkg/controllers/backup.(*OperatorController).scheduleBackup
Where may the  issue ???
