### ISSUE TITLE
Helm chart broken (v1 vs v1alpha1 and RBAC)

### ISSUE THREAD

**Issue by prydie** [oracle/mysql-operator#135]
Currently, we don't version the mysql-operator helm chart so the chart from master is used to install the operator independent of the version of the operator being installed. The change of API version to v1alpha1 means that the helm chart on master is incompatible with the latest release (and will be for all 0.1.x).

We should dispatch on the version in the CRD template and if it matches 0.1.x use the old CRD definitions with API version v1 and the `MySQL` prefixed Kinds.

Additionally v0.1.x requires read on ConfigMaps in the RBAC template.

**Comment by simonlord** [comment]
Shouldn't we just upload the helm chart as assets of the release - and have users use that to install?

**Comment by prydie** [comment]
Presuming you can install directly from a GH release then yes that would be a better solution (though we'd need to back publish).
