### ISSUE TITLE
Tutorial-attempt-06-18-2018 err in setting mysql password secret

### ISSUE THREAD

**Issue by ankurshah7** [oracle/mysql-operator#150]
I see that issue  [135](https://github.com/oracle/mysql-operator/issues/135) is fixed now. I followed tutorial again and have following to report.
1. YAML examples needed edit - change namespace to default and change CRD to MySQLCluster.
2. After creating 'myappdb' cluster, secret for 'myappdb-root-password' did not get created.

Here's log line from mysql-opeartor.

> E0618 18:17:20.634834       1 controller.go:320] error syncing 'default/myappdb': could not get secrets from cluster 'default/myappdb': secrets "myappdb-root-password" is forbidden: User "system:serviceaccount:mysql-operator:mysql-operator" cannot get secrets in the namespace "default"

Studying 02-rbac.yaml - rules are set for mysql-operator  namespace!

**Comment by prydie** [comment]
Hi @ankurshah7, thanks for the feedback!

You're running into two issues here. The first issue is that we're in the process of finishing up the next release that makes some major changes to the CRDs and downgrading the API group to v1alpha1 to better enable future iteration. Unfortunately, as our docs are here on Github it's very confusing at the moment. The documentation should be accurate on https://github.com/oracle/mysql-operator/tree/release-0.1, however.

These changes have also broken the helm chart on master for installing 0.1.x. I've opened #151 to track addressing the issue.
