### ISSUE TITLE
Custom Resource Kind name incorrect in Documentation

### ISSUE THREAD

**Issue by devdattakulkarni** [oracle/mysql-operator#154]
BUG REPORT

## Versions

**MySQL Operator Version**: Latest code from master (sha: 2a251f7c0886a8302a63f59a34858047ea88127f)

**Environment**:
- **Kubernetes version** (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2018-01-26T19:04:38Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: Minikube

- **OS** (e.g. from /etc/os-release): Mac OS X 10.11.4 (El Capitan)

- **Kernel** (e.g. `uname -a`): Darwin Devs-MacBook.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64 

## What happened?

Following the documentation I tried to create a custom resource with following definition

apiVersion: mysql.oracle.com/v1
kind: Cluster
metadata:
  name: myappdb

This did not work.

Looks like the name of the kind is actually MySQLCluster. Following worked:

apiVersion: mysql.oracle.com/v1
kind: MySQLCluster
metadata:
  name: myappdb

**Comment by cpanato** [comment]
PR here: https://github.com/oracle/mysql-operator/pull/156

**Comment by devdattakulkarni** [comment]
@cpanato I have added a comment on the PR.

**Comment by prydie** [comment]
Apologies for the confusion. This should be resolved now with the release of v0.2.0.
