### ISSUE TITLE
Restore from S3 but the back was not generated by the operator

### ISSUE THREAD

**Issue by cpanato** [oracle/mysql-operator#159]
Hello!

I have a question regarding restores.
How can I restore a DB using S3 or other supported storage but this backup was not generated by the operator. This is an existing backup that I would like to restore using the operator.

Is that possible?

thanks!

**Comment by owainlewis** [comment]
Hi @cpanato that isn't something we explicitly support currently but it's a valid and interesting use case. 

The obvious way to do this would be to create a new cluster and create a backup. Then in S3 replace the backup file with your existing backup and do a restore from that. It's not something we've tested though.

Hope that helps.

Thanks.

**Comment by cpanato** [comment]
@owainlewis Thanks for the answer! I will try!
