### ISSUE TITLE
Error creating 

### ISSUE THREAD

**Issue by CaptTofu** [oracle/mysql-operator#166]
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**MySQL Operator Version**:
iad.ocir.io/oracle/mysql-operator:0.1.1

**Environment**:
Oracle Cloud OKE

- **Kubernetes version** (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.10", GitCommit:"bebdeb749f1fa3da9e1312c4b08e439c404b3136", GitTreeState:"clean", BuildDate:"2017-11-03T17:13:44Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-2+b35c8f02b79855", GitCommit:"b35c8f02b79855c762b0da3afdc643ba1aef1ca9", GitTreeState:"clean", BuildDate:"2018-06-01T21:03:42Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
Oracle
- **OS** (e.g. from /etc/os-release):
OCI
- **Kernel** (e.g. `uname -a`):
n/a
- **Others**:

## What happened?
I'm preparing to present a talk on the MySQL Operator to the APAC cloud group Tried to apply the sample cluster.yaml:
```
---

apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: test-app-db
  namespace: capttofu
```
 and was given the error: error: 

```unable to recognize "cluster.yaml": no matches for mysql.oracle.com/, Kind=Cluster```

## What you expected to happen?
mysqlcluster created

## How to reproduce it (as minimally and precisely as possible)?
after installing the operator helm chart, apply the sample cluster.yaml

## Anything else we need to know?
https://github.com/oracle/mysql-operator/blob/master/docs/tutorial.md#create-a-simple-mysql-cluster, I'm unable to get the cluster.yaml applied with the following error:
```
kubectl apply -f cluster.yaml 
error: unable to recognize "cluster.yaml": no matches for mysql.oracle.com/, Kind=Cluster
```

Everything looks good:
```
helm list
NAME          	REVISION	UPDATED                 	STATUS  	CHART               	NAMESPACE
mysql-operator	1       	Tue Jul  3 23:11:19 2018	DEPLOYED	mysql-operator-0.1.0	default  
```
```
kubectl get customresourcedefinition
NAME                                    KIND
mysqlbackups.mysql.oracle.com           CustomResourceDefinition.v1beta1.apiextensions.k8s.io
mysqlbackupschedules.mysql.oracle.com   CustomResourceDefinition.v1beta1.apiextensions.k8s.io
mysqlclusters.mysql.oracle.com          CustomResourceDefinition.v1beta1.apiextensions.k8s.io
mysqlrestores.mysql.oracle.com          CustomResourceDefinition.v1beta1.apiextensions.k8s.io
```

**Comment by owainlewis** [comment]
Hi @CaptTofu 

This is a temporary problem with our documentation as we prepare for a new MySQL 8 release. The CustomResourceDefinitions and (kind and apiVersion) were changed recently. Essentially the examples in the manifest directory are aimed at the master branch. For the 0.1.1 release, the following example should work:

```yaml
apiVersion: mysql.oracle.com/v1
kind: MySQLCluster
metadata:
  name: mysql
```

**Comment by CaptTofu** [comment]
thank you!
