### ISSUE TITLE
Export logs in E2E tests

### ISSUE THREAD

**Issue by prydie** [oracle/mysql-operator#177]
Currently, we debug failed E2E tests by skipping deletion of the specific test namespace on failure thereby leaving the resources available for inspection. This will no longer apply to all users once third-party developers can trigger CI via pull requests.

We should delete namespaces even on failure and export the following logs as artefacts of the pipeline:

 - MySQL Operator container logs
 - All MySQL server instances
 - All mysql-agent instances

Related: #97

**Comment by harveylowndes** [comment]
Looking into this now. Just wondering if you can give a clarification on what is meant by 
`All MySQL server instances
All mysql-agent instances`?

**Comment by prydie** [comment]
@harveylowndes By that, I mean that we should export the logs of all containers in the test namespace(s) corresponding to failures  (see: `kubectl cluster-info dump --namespace` / https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/clusterinfo_dump.go)
