### ISSUE TITLE
Error using  mysql-agent with Kops

### ISSUE THREAD

**Issue by mareimorsy** [oracle/mysql-operator#190]
Could you please update the mysql-agent image?
The logs gives me this error : "Error bootstrapping cluster: getting CIDR to whitelist for  GR: pod IP "100.96.5.46" is not a private IPv4 address"
There is a bug fix here:
CIDR fixes and kops support
https://github.com/oracle/mysql-operator/pull/184
It has merged but it didn't release yet ... Please build a new image as soon as possible

**Comment by prydie** [comment]
Resolved with the 0.3.0 release. Sorry this took so long @mareimorsy!
