### ISSUE TITLE
Installing operator in a different namespace fails

### ISSUE THREAD

**Issue by mateusz-blaszkowski** [oracle/mysql-operator#193]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**MySQL Operator Version**:

https://github.com/oracle/mysql-operator/commit/92fa62455e72f87935ac16d4c7a4260c43d3f3ea

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```
$ cat /etc/os-release 
NAME=Buildroot
VERSION=2018.05
ID=buildroot
VERSION_ID=2018.05
PRETTY_NAME="Buildroot 2018.05"
```
- **Kernel** (e.g. `uname -a`):
```
Linux minikube 4.15.0 #1 SMP Mon Jul 16 20:23:29 UTC 2018 x86_64 GNU/Linux
```
- **Others**:

## What happened?
Installing operator in a different namespace fails. Replica set cannot create a pod because "mysql-operator" serviceaccount is not found:
```
kubectl describe rs mysql-operator-56cb675b7f -n oracle-mysql-operator
...
Error creating: pods "mysql-operator-56cb675b7f-" is forbidden: error looking up service account oracle-mysql-operator/mysql-operator: serviceaccount "mysql-operator" not found
```

I've found that mysql-operator serviceaccount is indeed created but in a default (mysql-operator) namespace:
```
# kubectl get sa  mysql-operator -n mysql-operator
NAME             SECRETS   AGE
mysql-operator   1         16m
```

## What you expected to happen?
I'd expect the serviceaccount mysql-operator to be created in a specified namespace

## How to reproduce it (as minimally and precisely as possible)?
```
kubectl create ns oracle-mysql-operator
helm install --name oracle-mysql-operator --set operator.namespace=oracle-mysql-operator mysql-operator
kubectl describe rs <rs_name> -n oracle-mysql-operator
# Here you should see an error saying that mysql-operator serviceaccount is not found 
```

**Comment by mateusz-blaszkowski** [comment]
I've just realized `operator.global` should be set to false in order for the service account to be created in the specified namespace. But shouldn't it be set to false automatically if operator.namespace is specified? :)

**Comment by owainlewis** [comment]
Thanks @mateusz-blaszkowski as you rightly pointed out we should probably handle this automatically.
