### ISSUE TITLE
"Cluster" in version "mysql.oracle.com/v1alpha1" not found

### ISSUE THREAD

**Issue by sssshah** [oracle/mysql-operator#196]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST
BUG REPORT

## Versions
K8 v 1.9.1
**MySQL Operator Version**:
Lesst
**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

**Comment by prydie** [comment]
Hi @sssshah, please can you provide a little more detail about the circumstances in which you're seeing this issue?

**Comment by sssshah** [comment]
Running on Oracle OKE
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-2+ff9181f92914d6", GitCommit:"ff9181f92914d638c93511c5163ac1e5dcbdf492", GitTreeState:"clean", BuildDate:"2018-04-24T22:19:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
