### ISSUE TITLE
openshift 3.10 cant not create mysql cluster

### ISSUE THREAD

**Issue by pennpeng** [oracle/mysql-operator#203]
## Versions

**MySQL Operator Version**:
0.2
**Environment**:
- **Kubernetes version** (use `kubectl version`):
ocp 3.10(1.10)
- **Cloud provider or hardware configuration**:
openstack
- **OS** (e.g. from /etc/os-release):
rhel 7.5
- **Kernel** (e.g. `uname -a`):

- **Others**:

## What happened?
```
1 controller.go:289] error syncing 'mysql-cluster/mysql': creating root password Secret: secrets "mysql-root-password" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: User "system:serviceaccount:mysql-operator:mysql-operator" cannot update mysqlclusters/finalizers.mysql.oracle.com in project "mysql-cluster", <nil>
```

**Comment by pennpeng** [comment]
the solutions:https://github.com/operator-framework/helm-app-operator-kit/issues/7

**Comment by prydie** [comment]
@pennpeng Would you mind testing the updated helm chart from https://github.com/oracle/mysql-operator/pull/204/commits/d1effcd8c498657a097008c3691fa648f13d5b08 as we don't generally test on OpenShift perchance?

**Comment by pennpeng** [comment]
I have passed the test
