### ISSUE TITLE
Questions with 2 TODO comments

### ISSUE THREAD

**Issue by Simon-Li** [oracle/mysql-operator#211]
Not sure whether the next 2 TODOs are still valid or not? @prydie 

In agent controller, there is a `UpdateFunc` already added for `backupInformer` as below.

https://github.com/oracle/mysql-operator/blob/ee732cf526e71e79bfd1611bccdedc139178c10a/pkg/controllers/backup/agent_controller.go#L126-L128

so this todo may no longer need?
https://github.com/oracle/mysql-operator/blob/ee732cf526e71e79bfd1611bccdedc139178c10a/pkg/controllers/backup/agent_controller.go#L281-L283

same for the operator controller side? my tests showed fixing validation error by running `kubectl apply -f` with correct backup.yaml works good.

https://github.com/oracle/mysql-operator/blob/ee732cf526e71e79bfd1611bccdedc139178c10a/pkg/controllers/backup/operator_controller.go#L257-L258

**Comment by prydie** [comment]
Hey @Simon-Li,

It looks to me like the TODO is still valid as there is no `UpdateFunc` declared in the operator controller. If the backup fails validation it won't be scheduled on an agent by my reading.

https://github.com/oracle/mysql-operator/blob/ee732cf526e71e79bfd1611bccdedc139178c10a/pkg/controllers/backup/operator_controller.go#L116-L136
