### ISSUE TITLE
Can I create mysql5.7 on the master branch?

### ISSUE THREAD

**Issue by wanghe-fit2cloud** [oracle/mysql-operator#253]
##Question
After the master branch is created successfully, we found that mysql version is 8.0.12. There is such a problem that whether mysql5.7.x version can be created on the master branch

## Versions
**MySQL Operator Version**:
- master branch

**Environment**:
- Kubernetes version 1.13.2

## What you expected to happen?
I want to create a mysql5.7 database on the master branch

**Comment by owainlewis** [comment]
Hi @wanghe-fit2cloud 

We dropped support for MySQL 5.7 and now only support 8.0.11 as a minimum version.

**Comment by purebluesong** [comment]
Is any idea to use MySQL 5.7?
