### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by cpanato** [oracle/mysql-operator#255]
we are planning to use the operator in production but looks like no more commits or updates.

**Comment by delgod** [comment]
Hi @cpanato,

it is alive, Oracle MySQL Operator is a featureful operator, works fine, I haven't found any critical bugs, it is based on MySQL 8.0

you can also look into other MySQL Operators
- https://github.com/Percona-Lab/percona-xtradb-cluster-operator
- https://github.com/presslabs/mysql-operator

if you really need sharding - you can look into
- https://github.com/vitessio/vitess-operator
- https://github.com/pingcap/tidb-operator

**Comment by owainlewis** [comment]
@cpanato Hey. No the project is still active but has been pretty quiet for a while now. Please let me know if you have any specific questions about features or roadmap etc.

**Comment by cpanato** [comment]
@owainlewis thanks! i think we will start using this with our operator 😄 thanks!

**Comment by alsbury** [comment]
The readme file suggests this operator should not be used for production. Is that still true?

**Comment by bweston92** [comment]
@alsbury this operator hasn't been maintained and does not support Kubernetes after 1.16.
