### ISSUE TITLE
how to backup and restore in local

### ISSUE THREAD

**Issue by linqingping** [oracle/mysql-operator#266]
how to backup and restore in local ?
https://github.com/oracle/mysql-operator/blob/master/examples/cluster/cluster-with-data-volume-and-backup-volume.yaml
the example backupVolume how to use?

**Comment by prydie** [comment]
Hi @linqingping. The only currently supported backup/restore mechanism is via an S3 compatible object storage backend. The easiest way to facilitate that locally would be using an in-cluser [Minio](https://github.com/minio/minio) setup.
