### ISSUE TITLE
how to use backup ？

### ISSUE THREAD

**Issue by linqingping** [oracle/mysql-operator#267]
the cluster yaml from 
https://github.com/oracle/mysql-operator/blob/master/examples/cluster/cluster-with-data-volume-and-backup-volume.yaml

**Comment by prydie** [comment]
Hi @linqingping. The backup volume is a historical artefact of when we wrote backups to disk prior to uploading them to object storage. We should flag it up as deprecated and remove it from the documentation / examples.

Documentation on backup up to an S3 compatible object storage backend can be found [here](https://github.com/oracle/mysql-operator/blob/master/docs/user/backup.md).

**Comment by linqingping** [comment]
thank you
