### ISSUE TITLE
Not able to bring up the cluster

### ISSUE THREAD

**Issue by sivachirravuri** [oracle/mysql-operator#269]
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**MySQL Operator Version**: 0.2.0

**Environment**: aws
- **Kubernetes version** (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**: aws
- **OS** (e.g. from /etc/os-release):NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- **Kernel** (e.g. `uname -a`): Linux osboxes 4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- **Others**:

## What happened?

Operator installed.. able to see the crds.

 kubectl get crd
NAME                                    AGE
mysqlbackups.mysql.oracle.com           <invalid>
mysqlbackupschedules.mysql.oracle.com   <invalid>
mysqlclusters.mysql.oracle.com          <invalid>
mysqlrestores.mysql.oracle.com          <invalid>

## How to reproduce it (as minimally and precisely as possible)?

kubectl create -f cluster.yaml
error: unable to recognize "cluster.yaml": no matches for mysql.oracle.com/, Kind=Cluster

**Comment by prydie** [comment]
Hi @sivachirravuri, you're using version 0.2 but applying a 0.3 CRD. Please try again with the latest version of the Operator installed.
