### ISSUE TITLE
Error creating cluster using examples/cluster/cluster.yaml

### ISSUE THREAD

**Issue by amitoj** [oracle/mysql-operator#61]
Hi,

Following instructions from the tutorial to create a simple MySQL cluster,

`kubectl apply -f cluster.yaml`

I get the following error message

> error: unable to recognize "cluster.yaml": no matches for mysql.oracle.com/, Kind=MySQLCluster

Tried this on both minikube (v0.25.2) and Google GKE.

Thanks

**Comment by templecloud** [comment]
It looks like the required MySQLOperator [custom resource definitions](https://github.com/oracle/mysql-operator/blob/master/mysql-operator/templates/01-resources.yaml) are not installed into your cluster, or, cannot be found.

How did you install the operator into your test clusters? Something might have gone wrong during that step, and, left your clusters missing these resources.

**Comment by owainlewis** [comment]
Hi @amitoj 

I deployed to Google GKE using Helm and it appears to work OK for me. The error above suggests that the CRD's are not installed correctly. How did you install the operator?

For reference I did the following on a vanilla GKE cluster. 

```
# Install helm (https://github.com/kubernetes/helm/blob/master/docs/rbac.md)
helm install mysql-operator --name mysqloperator --set rbac.enabled=true
kubectl create -f examples/cluster/cluster.yaml
```

**Comment by amitoj** [comment]
Thanks @owainlewis @templecloud 
I think I may have deleted the helm chart.
I've successfuly created MySQL cluster now using the tutorial.

**Comment by benmathews** [comment]
I'm seeing this error myself. The crd are installed. 

```
$ k get customresourcedefinition 
NAME                                    AGE
mysqlbackups.mysql.oracle.com           6m
mysqlbackupschedules.mysql.oracle.com   6m
mysqlclusters.mysql.oracle.com          6m
mysqlrestores.mysql.oracle.com          6m

```

Any other debugging tips?

**Comment by CaptTofu** [comment]
Hi all- I'm encountering this error and have followed the tutorial verbatim:

---

{code}
apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: test-app-db
  namespace: capttofu
{code}

Then:

{code}
kubectl apply -f cluster.yaml 
error: unable to recognize "cluster.yaml": no matches for mysql.oracle.com/, Kind=Cluster
{code}

If I look at the logs for the operator pod it looks good:

{code}
I0704 03:11:39.498795       1 shared_informer.go:122] caches populated
I0704 03:11:39.499087       1 cache.go:37] Caches are synced for mysql cluster controller
I0704 03:11:39.499095       1 shared_informer.go:122] caches populated
I0704 03:11:39.499119       1 cache.go:37] Caches are synced for operator-restore-controller controller
I0704 03:11:39.499139       1 operator_controller.go:180] Caches are synced
I0704 03:11:39.499105       1 controller.go:276] Starting MySQLCluster controller workers
I0704 03:11:39.499185       1 controller.go:282] Started MySQLCluster controller workers
I0704 03:11:39.498961       1 shared_informer.go:122] caches populated
I0704 03:11:39.499247       1 cache.go:37] Caches are synced for operator-backup-controller controller
I0704 03:11:39.499258       1 operator_controller.go:169] Caches are synced
I0704 03:11:39.500243       1 shared_informer.go:122] caches populated
I0704 03:11:39.500265       1 controller.go:147] Backup schedule controller caches are synced

{code}
