### ISSUE TITLE
Unable to mount data volume to multi-master replica based on example

### ISSUE THREAD

**Issue by ocastle** [oracle/mysql-operator#71]
BUG REPORT

## Versions

**MySQL Operator Version**:
0.1.0

**Environment**:
- **Kubernetes version** (use `kubectl version`):
    Client: 1.9.2
    Server: 1.7.5
- **Cloud provider or hardware configuration**:
Azure
- **OS** (e.g. from /etc/os-release):
    Ubuntu 16.04.2 LTS
Linux
- **Kernel** (e.g. `uname -a`):
    4.4.0-119-generic
- **Others**:
https://github.com/oracle/mysql-operator

## What happened?
Following the example attaching a volume, to a mulimaster cluster of 3 errors about directory 
'/tmp/data' does not exist and never progresses with provisioning. Sticking to the default and creating 
an EmptyDir works fine.

Pod Status:     lstat /tmp/data: no such file or directory

## What you expected to happen?
Expected for the persistent volume to be created and attached to each pod of the cluster.

## How to reproduce it (as minimally and precisely as possible)?
Using the following manifest:
```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
    app: mysql-multimaster-cluster
  name: mysql-local-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  hostPath:
    path: /tmp/data
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
---
apiVersion: "mysql.oracle.com/v1"
kind: MySQLCluster
metadata:
  name: mysql-multimaster-cluster
  labels:
    app: mysql-multimaster-cluster
spec:
  multiMaster: true
  replicas: 3
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: manual
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi
```
## Anything else we need to know?
kublet log entry:
```bash
pr 09 16:42:02 k8s-default-10099566-2 docker[3490]: I0409 16:42:02.505704    3580 kuberuntime_manager.go:457] Container {Name:mysql Image:mysql/mysql-server:5.7.20-1.1.2 Command:[/bin/bash -ecx # Note: We fiddle with the resolv.conf fil
Apr 09 16:42:02 k8s-default-10099566-2 docker[3490]:          # can refer to each other using just thier hostnames (e.g. mysql-N), thus do not need
Apr 09 16:42:02 k8s-default-10099566-2 docker[3490]:          # to qualify their names with the name of the (headless) service (e.g. mysql-N.mysql)
Apr 09 16:42:02 k8s-default-10099566-2 docker[3490]:          search=$(grep ^search /etc/resolv.conf)
Apr 09 16:42:02 k8s-default-10099566-2 docker[3490]:          echo "$search mysql-multimaster-cluster.${POD_NAMESPACE}.svc.cluster.local" >> /etc/resolv.conf
Apr 09 16:42:02 k8s-default-10099566-2 docker[3490]:          # Finds the replica index from the hostname, and uses this to define
Apr 09 16:42:02 k8s-default-10099566-2 docker[3490]:          # a unique server id for this instance.
Apr 09 16:42:02 k8s-default-10099566-2 docker[3490]:          index=$(cat /etc/hostname | grep -o '[^-]*$')
Apr 09 16:42:02 k8s-default-10099566-2 docker[3490]:          /entrypoint.sh --server_id=$(expr 1000 + $index) --user=mysql --datadir=/var/lib/mysql --log-error=/var/lib/mysql/mysqld.err --default-storage-engine=innodb --default-tmp-stor
Apr 09 16:42:02 k8s-default-10099566-2 docker[3490]: f:nil,SecretKeyRef:&SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:mysql-multimaster-cluster-root-password,},Key:password,Optional:nil,},}} {Name:MYSQL_ROOT_HOST Valu
Apr 09 16:42:02 k8s-default-10099566-2 docker[3490]: I0409 16:42:02.505861    3580 kuberuntime_manager.go:457] Container {Name:mysql-agent Image:wcr.io/oracle/mysql-agent:0.1.0 Command:[] Args:[--v=4] WorkingDir: Ports:[] EnvFrom:[] Env:
Apr 09 16:42:02 k8s-default-10099566-2 docker[3490]: E0409 16:42:02.510681    3580 kuberuntime_manager.go:718] container start failed: lstat /tmp/data: no such file or directory: Generate Container Config Failed
Apr 09 16:42:02 k8s-default-10099566-2 docker[3490]: E0409 16:42:02.513152    3580 kuberuntime_manager.go:718] container start failed: lstat /tmp/data: no such file or directory: Generate Container Config Failed
Apr 09 16:42:02 k8s-default-10099566-2 docker[3490]: E0409 16:42:02.513286    3580 pod_workers.go:182] Error syncing pod 518c03de-3c14-11e8-9f11-000d3a71c393 ("mysql-multimaster-cluster-0_default(518c03de-3c14-11e8-9f11-000d3a71c393)"),
Apr 09 16:42:02 k8s-default-10099566-2 docker[3490]: , failed to "StartContainer" for "mysql-agent" with lstat /tmp/data: no such file or directory: "Generate Container Config Failed"
Apr 09 16:42:02 k8s-default-10099566-2 docker[3490]: ]
```

**Comment by ocastle** [comment]
Part of the issue is that the directory path /tmp/data does not exist for the **mysql/mysql-servers:5.7.20-1.1.2** container used to create the statefulset. I know the database data is created/stored under **/var/lib/mysql**. Is the example path, just that an example path or is there a reason that was chosen for the example? Assuming there might be something done with that directory from the mysql-operator side of things to orchestrate replication between the multi-masters.

**Comment by gites** [comment]
@ocastle the ` /tmp/data` directory needs to exist on all k8s nodes that will have MySQL PODs running. If it doesn't exist you need to create it manually. You can also choose to use different directory that already exists (`/tmp` for example). This directory doesn't have anything common with cluster replication stuff - it's just a part of storage definition for a k8s cluster.

**Comment by prydie** [comment]
Thanks @gites.

Closing for now. If you have any further problems @ocastle do let us know.

**Comment by ocastle** [comment]
I understand why the ticket is closed, but I do have a question that follows this thread. Based on the example, I assumed that it had some weight in terms of creating a data volume to hold your data to allow a starting point if a pod were to crash. While at the same time ensuring that there is always something present if for some reason all replicas were to crash and lose the ability to replicate from another machine.

**Comment by prydie** [comment]
Hi @ocastle,

The the `volumeClaimTemplate` (if provided) is used to create a separate [persistant volume claim](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) for each member of the MySQLCluster which the MySQL container uses as its data directory. You can change the volume type to match your storage solution in your Kubernetes environment.

Using a [hostPath volume](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) volume can be useful in situations where you want to pin a MySQLCluster to certian nodes in your Kubernetes cluster and use fast host-local storage (i.e. NVMe SSD) rather than network-attached storage. The `path: /tmp/data` needs to be manually provisioned on _each_ Kubernetes node that the MySQLCluster is scheduled on.

If a volume claim template isn't provided the Operator uses a [emptyDir volume](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir) instead.

**Comment by ocastle** [comment]
Thanks @prydie for the explanation of how that code functions. I wasn't wrapping my head around it when I was looking over it. I do see the data volume populating within my `/tmp` directory of the k8's node. My objective was to use something like an `azurefile` or `azuredisk` that is tied to the pod and could follow if it were scheduled/moved to another node.
