### ISSUE TITLE
Simplify deployment. Do we really need Helm?

### ISSUE THREAD

**Issue by owainlewis** [oracle/mysql-operator#79]
Most operators can be installed without Helm. Should we revert to simple YAML deployments?

**Comment by bweston92** [comment]
Kubernetes config can sometimes be overwhelming, also when you spread stuff across files (not that there is too many right now) it is more vulnerable to typos and other mistakes.

Having a single `values.yml` file makes it much less error prone imo.

**Comment by harveylowndes** [comment]
Addressed and documented in #118

**Comment by prydie** [comment]
We're currently going to stick with Helm, however, will maintain independent manifests for dev setup.
