### ISSUE TITLE
Rethink cluster args (do we need all of them)

### ISSUE THREAD

**Issue by owainlewis** [oracle/mysql-operator#80]
The MySQL Operator initialises with the cluster args defined here. https://github.com/oracle/mysql-operator/blob/master/pkg/resources/statefulsets/statefulset.go#L163

These were based on some recommendation and examples but in retrospect some of these appear invalid and we should aim to remove as many as possible since the args here will take precedence over anything defined by a user in configuration.

**Comment by gites** [comment]
Only minimal set os args required for seting up group replication should be used here.
