### ISSUE TITLE
Implement support for Pod Security Policies (PSPs)

### ISSUE THREAD

**Issue by prydie** [oracle/mysql-operator#82]
https://kubernetes.io/docs/concepts/policy/pod-security-policy/

Example: https://github.com/coreos/etcd-operator/blob/master/doc/user/spec_examples.md#custom-pod-security-context

**Comment by MadalinaPatrichi** [comment]
Isn't this handled automatically via the use of Stateful Sets?

**Comment by prydie** [comment]
@MadalinaPatrichi It is handled in the StatefulSet via [`.spec.template`](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/types.go#L122). The StatefulSet is an implementation detail that we don't expect users to manipulate directly, however. We just need to add a field to our Cluster resource and then pass that down to the StatefulSet.

**Comment by KashifSaadat** [comment]
I believe this is now covered via PR #218
