### ISSUE TITLE
resolv.conf fiddling fails for custom cluster dns names 

### ISSUE THREAD

**Issue by simplysoft** [oracle/mysql-operator#84]
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**MySQL Operator Version**: `0.1.0`

**Environment**:
- **Kubernetes version** (use `kubectl version`):
`
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:50:45Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
`

- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): `coreos 1688.5.3`
- **Kernel** (e.g. `uname -a`): `Linux 4.14.32-coreos`

## What happened?

```
cat <<'YAML' | kubectl apply -f -
apiVersion: mysql.oracle.com/v1
kind: MySQLCluster
metadata:
  name: clusterdb
spec:
  multiMaster: true
  replicas: 2
YAML
```
clusterdb-0 starts up nicely, but then clusterdb-1 stuck during startup (clusterdb-1 mysql is actually up and running, but mysql-agent not)
```
clusterdb-1 mysql-agent] ERROR: logging before flag.Parse: I0418 15:27:39.335504       1 cluster_manager.go:127] Cluster not yet present. Waiting... 
```

## What you expected to happen?

Database starts up

## How to reproduce it (as minimally and precisely as possible)?

Setup kubernetes cluster with a DNS name different than "cluster.local", e.g. `k8s-test.local`

## Anything else we need to know?

custer.local is currently hard-coded in https://github.com/oracle/mysql-operator/blob/f3b89a4a8fb01a2c8aa13a67a4c7735861fb7dab/pkg/resources/statefulsets/statefulset.go#L220

Either the script should properly read out resolve.conf and produce the correct search entry or the cluster dns name should be configurable in the operator

**Comment by prydie** [comment]
Thanks for the bug report @simplysoft.

@kristenjacobs / @garthy If I recall correctly this works around a limit on the hostname in mysql-server of ~64 characters doesn't it?

I think the best approach would be to address cluster members by `${cluster_name}-${statefulset_ordinal}.${cluster_name}.${cluster_namespace}` and add validation to MySQLCluster to check that this is below the limit on cluster creation.

**Comment by jhorwit2** [comment]
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id

This is a stateful set feature and what other operators do as well like ETCD. Because the default resolv includes a bunch of search domains you could even get away w/o the namespace but that'd require anything using the hostname to be in the same namespace.

**Comment by prydie** [comment]
@jhorwit2 Awesome. I don't think thats a problem as I believe its only for member-member communication which due to the StatefulSet will always be in the same namespace.

**Comment by kristenjacobs** [comment]
The character limit on hostnames, while being an issue, wasn't the only reason that we fiddle with the resolv.conf. From what I remember, even if the fully qualified name was used everywhere in the MySQL configuration, MySQL was still internally only using the hostname part, thus unless this was resolvable, the cluster would not form. This, along with the fact that just using the hostname meant that were we less likely to hit the character limit, was why we stuck with the resolve.conf updating. 

However, I just had a dig around in some correspondence with the mysql team, and setting the --report-host to the fqdn on each of the mysql instances looks like a promising option that we haven't tried yet. (See: https://bugs.mysql.com/bug.php?id=83128). Maybe using this option, along with using the fqdn everywhere, i.e. in the group seeds and all calls from the mysqlshell, would allow us to remove the search domain from the resolve.conf. If this doesn't work, then it might be that we have to make the search domain configurable..
