### ISSUE TITLE
MySQL Group Replication Secure Socket Layer Support (SSL)

### ISSUE THREAD

**Issue by owainlewis** [oracle/mysql-operator#89]
The MySQL Operator does not currently support SSL by default for Group Repliation. 

We should document how to configure SSL for Group Replication and (potentially?) implement it by default using self signed certs.

Reference

* https://dev.mysql.com/doc/refman/8.0/en/group-replication-secure-socket-layer-support-ssl.html

**Comment by prydie** [comment]
Care will need to be taken around certificate lifecycle management (i.e. test what happens when certs are rotated).

**Comment by drobinson123** [comment]
Rather than using self-signed certificates you may be able to use kubernetes to manage the certificates:

https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/

**Comment by gites** [comment]
I would be awesome to have this integrated with HashiCorp Vault PKI, as one of the available options. https://www.vaultproject.io/api/secret/pki/index.html

**Comment by prydie** [comment]
I'd suggest we add a TLS secret to the MySQLCluster spec which could be populated by a wide variety of PKI mechanisms.
