### ISSUE TITLE
Init scripts

### ISSUE THREAD

**Issue by bweston92** [oracle/mysql-operator#92]
## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

## What?

When I create a database cluster specify a volume which holds init scripts which are then run against the server.

A bit like: https://github.com/docker-library/mysql/blob/2e4f2224f31e101d07c1e6a7c0da8245fde725c9/8.0/docker-entrypoint.sh#L178

**Comment by tboerger** [comment]
I think it's more common to use config maps for that

**Comment by owainlewis** [comment]
I think for simplicity we'd like to avoid going down this route. What kind of init scripts were you thinking of running? User creation and database setup is something we've discussed but decided it was probably beyond the scope of this operator and can be achieved in other ways.

**Comment by owainlewis** [comment]
Closing as we don't plan of adding this feature currently.
